[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log
startretries=5
startsecs=3

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm.log
startretries=5
startsecs=3

[program:horizon]
command=php /var/www/html/artisan horizon
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/horizon.log
stderr_logfile=/var/log/supervisor/horizon.log
user=www-data
startretries=5
startsecs=10
stopwaitsecs=60

[program:schedule]
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/schedule.log
stderr_logfile=/var/log/supervisor/schedule.log
user=www-data
startretries=5
startsecs=10

[program:reverb]
command=php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=18081
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/reverb.log
stderr_logfile=/var/log/supervisor/reverb.log
user=www-data
startretries=5
startsecs=10
